import type { AuditLog } from "./auditLogs.types";

export const auditLogsMock: AuditLog[] = [
  {
    id: "log-001",
    user: "admin@ministere.fr",
    action: "DELETE_DOC",
    resource: "budget_2026_confidentiel.pdf",
    status: "FAILED",
    level: "CRITICAL",
    ip: "192.168.1.105",
    timestamp: "2026-03-22T10:32:15.000Z",
    details: {
      message: "Tentative de suppression d'un document protege.",
      endpoint: "/api/documents/delete",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      payload: { docId: "doc_12345", reason: "manual_deletion", force: true },
      metadata: { department: "Finances", sensitivity: "confidentiel" },
    },
  },
  {
    id: "log-002",
    user: "user.suspect@external.com",
    action: "FAILED_LOGIN",
    resource: "Portail d'administration",
    status: "FAILED",
    level: "CRITICAL",
    ip: "203.0.113.45",
    timestamp: "2026-03-22T10:28:42.000Z",
    details: {
      message: "Cinquieme tentative de connexion echouee en dix minutes.",
      endpoint: "/api/auth/login",
      userAgent: "curl/7.68.0",
      payload: { email: "user.suspect@external.com", attempts: 5 },
      metadata: { source: "external-network" },
    },
  },
  {
    id: "log-003",
    user: "directeur@ministere.fr",
    action: "LOGIN",
    resource: "Portail d'administration",
    status: "SUCCESS",
    level: "INFO",
    ip: "192.168.1.10",
    timestamp: "2026-03-22T10:15:20.000Z",
    details: {
      message: "Connexion reussie depuis le bureau principal.",
      endpoint: "/api/auth/login",
      userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
      payload: { email: "directeur@ministere.fr", method: "sso" },
      metadata: { location: "Siege" },
    },
  },
  {
    id: "log-004",
    user: "admin@ministere.fr",
    action: "PERMISSION_CHANGE",
    resource: "Groupe Finance - 15 utilisateurs",
    status: "WARNING",
    level: "INFO",
    ip: "192.168.1.105",
    timestamp: "2026-03-22T09:45:10.000Z",
    details: {
      message: "Modification des permissions pour le groupe Finance.",
      endpoint: "/api/permissions/update",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      payload: { groupId: "grp_finance", permissions: ["read", "write", "delete"] },
      metadata: { changedBy: "admin" },
    },
  },
  {
    id: "log-005",
    user: "comptable@ministere.fr",
    action: "UPLOAD",
    resource: "rapport_mensuel_mars.xlsx",
    status: "SUCCESS",
    level: "INFO",
    ip: "192.168.1.50",
    timestamp: "2026-03-22T09:30:05.000Z",
    details: {
      message: "Document comptable televerse avec succes.",
      endpoint: "/api/documents/upload",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      payload: { fileName: "rapport_mensuel_mars.xlsx", size: 2048576, category: "financial" },
    },
  },
  {
    id: "log-006",
    user: "secretaire@ministere.fr",
    action: "UPDATE",
    resource: "dossier_personnel_emp_456",
    status: "SUCCESS",
    level: "INFO",
    ip: "192.168.1.75",
    timestamp: "2026-03-22T09:00:30.000Z",
    details: {
      message: "Mise a jour des informations du dossier.",
      endpoint: "/api/documents/update",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      payload: { docId: "doc_emp_456", fields: ["address", "phone"] },
    },
  },
  {
    id: "log-007",
    user: "directeur@ministere.fr",
    action: "EXPORT_REPORT",
    resource: "Synthese hebdomadaire",
    status: "SUCCESS",
    level: "INFO",
    ip: "192.168.1.10",
    timestamp: "2026-03-22T08:52:14.000Z",
    details: {
      message: "Export du rapport de supervision.",
      endpoint: "/api/reports/export",
      userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
      payload: { format: "pdf", scope: "weekly_overview" },
    },
  },
  {
    id: "log-008",
    user: "agent.rh@ministere.fr",
    action: "VIEW_RECORD",
    resource: "Dossier RH - agent_184",
    status: "WARNING",
    level: "INFO",
    ip: "192.168.1.91",
    timestamp: "2026-03-22T08:34:50.000Z",
    details: {
      message: "Consultation d'un dossier sensible en dehors des horaires habituels.",
      endpoint: "/api/records/view",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      payload: { recordId: "agent_184", sensitivity: "high" },
    },
  },
  {
    id: "log-009",
    user: "admin@ministere.fr",
    action: "DELETE_DOC",
    resource: "temp_draft_notes.txt",
    status: "SUCCESS",
    level: "INFO",
    ip: "192.168.1.105",
    timestamp: "2026-03-22T08:30:15.000Z",
    details: {
      message: "Suppression d'un document temporaire.",
      endpoint: "/api/documents/delete",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      payload: { docId: "doc_temp_789", permanent: false },
    },
  },
  {
    id: "log-010",
    user: "secops@ministere.fr",
    action: "POLICY_UPDATE",
    resource: "Politique d'acces admin",
    status: "SUCCESS",
    level: "INFO",
    ip: "192.168.1.210",
    timestamp: "2026-03-21T17:42:11.000Z",
    details: {
      message: "Mise a jour des regles d'acces admin.",
      endpoint: "/api/security/policies",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
      payload: { policy: "admin_access", version: "3.2" },
    },
  },
  {
    id: "log-011",
    user: "comptable@ministere.fr",
    action: "DOWNLOAD_DOC",
    resource: "etat_depenses_fevrier.pdf",
    status: "SUCCESS",
    level: "INFO",
    ip: "192.168.1.50",
    timestamp: "2026-03-21T16:08:27.000Z",
    details: {
      message: "Telechargement d'un document financier.",
      endpoint: "/api/documents/download",
      payload: { docId: "doc_fin_2202" },
    },
  },
];
